name: Deploy Microservice

on:
  push:
    branches:
      - dev  # Se ejecuta cuando hay cambios en main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/createuserservice:latest .
      
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/createuserservice:latest

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/createuserservice:latest
            docker stop createuserservice || true
            docker rm createuserservice || true
            docker run -d --name createuserservice -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/createuserservice:latest
            docker system prune -f
          EOF

