name: Deploy Microservices

on:
  push:
    branches:
      - dev # Se ejecuta solo si hay cambios en main
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changed microservices
        id: filter
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d'/' -f1 | sort -u)
          SERVICES=""
          for dir in $CHANGED; do
            if [[ -f "$dir/Dockerfile" ]]; then
              SERVICES="$SERVICES $dir"
            fi
          done
          echo "Detected changes in: $SERVICES"
          echo "services=$SERVICES" >> $GITHUB_ENV

  deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: ${{ env.services != '' }}
    strategy:
      matrix:
        service: ${{ fromJSON('["CreateUserService", "GetUserService", "LoginUserService"]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          cd ${{ matrix.service }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets[format('EC2_HOST_{0}', matrix.service)] }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            docker stop ${{ matrix.service }} || true
            docker rm ${{ matrix.service }} || true
            docker run -d --name ${{ matrix.service }} -p 80:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest
            docker system prune -f
          EOF
