
name: Deploy Get User Service

on:
  push:
    branches:
      - dev
    paths:
      - 'UserDomain/GetUserService/**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Forzar autenticación en Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1
          docker logout
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir imagen Docker
        run: |
          cd UserDomain/GetUserService
          docker build -t fernanyag20/getuserservice:latest .
          docker images | grep getuserservice || echo "🚨 Imagen no encontrada localmente"

      - name: Subir imagen a Docker Hub
        run: | 
          docker push fernanyag20/getuserservice:latest
          echo "✅ Imagen subida a Docker Hub"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Iniciar sesión en Docker Hub en EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_USERDOMAIN }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🚀 Iniciando sesión en Docker Hub en EC2..."
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Conectar a EC2 y actualizar contenedor
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_USERDOMAIN }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🛠 Verificando si Docker está instalado..."
            if ! command -v docker &> /dev/null
            then
                echo "⚠️ Docker no está instalado. Instalándolo..."
                sudo apt update -y
                sudo apt install -y docker.io
                sudo systemctl enable docker
                sudo systemctl start docker
            else
                echo "✅ Docker ya está instalado."
            fi

            echo "🔄 Eliminando imágenes antiguas..."
            docker stop getuserservice || echo "No existía un contenedor en ejecución"
            docker rm getuserservice || echo "No existía un contenedor previo"
            docker rmi alevm98/getuserservice:latest || echo "No había imagen previa para eliminar"

            echo "📥 Descargando nueva imagen desde Docker Hub..."
            docker pull fernanyag20/getuserservice:latest || { echo "🚨 Error al hacer pull de la imagen"; exit 1; }

            echo "🚀 Iniciando nuevo contenedor..."
            docker run -d --restart unless-stopped --name getuserservice -p 80:80 fernanyag20/getuserservice:latestt

            echo "🔍 Verificando contenedores activos..."
            docker ps -a
