name: CI/CD for Microservices

on:
  push:
    branches:
      - dev
    paths:
      - 'UserDomain/**'
      - 'PostDomain/**'
      - 'StoryDomain/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service_name: [ "createuserservice", "getcoverimageservice", "getuserinvitationsservice", "getuserrandom", "getuserservice", "getuserusernameservice", "getusersservice", "loginuserservice", "resetpasswordservice" ]
        service_path: [ "UserDomain/AcceptDenyInvitationService", "UserDomain/CreateUserService", "UserDomain/GetCoverImageService", "UserDomain/GetUserInvitationsService", "UserDomain/GetUserRandom", "UserDomain/GetUserService", "UserDomain/GetUserUsernameService", "UserDomain/GetUsersService", "UserDomain/LoginUserService", "UserDomain/ResetPasswordService" ]
        ec2_host: [ "${{ secrets.EC2_HOST_2 }}"]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changes
        id: check_changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "${{ matrix.service_path }}"; then
            echo "CHANGED=true" >> $GITHUB_ENV
          else
            echo "CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Build and push Docker image
        if: env.CHANGED == 'true'
        run: |
          docker build -t fernanyag20/${{ matrix.service_name }}:latest ${{ matrix.service_path }}
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push fernanyag20/${{ matrix.service_name }}:latest

      - name: Deploy to EC2
        if: env.CHANGED == 'true'
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ matrix.ec2_host }} << 'EOF'
            docker pull fernanyag20/${{ matrix.service_name }}:latest
            docker stop ${{ matrix.service_name }} || true
            docker rm ${{ matrix.service_name }} || true
            docker run -d --name ${{ matrix.service_name }} -p 80:80 fernanyag20/${{ matrix.service_name }}:latest
          EOF
