name: Deploy CreateUserService

on:
  push:
    paths:
      - 'UserDomain/CreateUserService/**'  # Solo detecta cambios en esta carpeta
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Iniciar sesión en Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Construir imagen Docker
      run: |
        cd UserDomain/CreateUserService
        docker build -t fernanyag20/createuserservice:latest .

    - name: Subir imagen a Docker Hub
      run: docker push fernanyag20/createuserservice:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Conectar a EC2 y actualizar contenedor
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull fernanyag20/createuserservice:latest
          docker stop createuserservice || true
          docker rm createuserservice || true
          docker run -d --name createuserservice -p 5050:5050 fernanyag20/createuserservice:latest
