  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: filter
        run: |
          # Obtiene los archivos modificados
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          
          echo "Archivos modificados detectados:"
          echo "$changed_files"

          # Identifica los microservicios que han cambiado
          services=$(echo "$changed_files" | awk -F'/' '{print $1}' | sort -u | uniq)

          # Forzar actualización si se modifican archivos clave en la raíz de cualquier microservicio
          for service in $services; do
            if [[ -f "$service/Dockerfile" || -f "$service/app.js" || -f "$service/package.json" || -f "$service/.env" ]]; then
              detected_services+="$service "
            fi
          done

          echo "Microservicios detectados para reconstrucción: $detected_services"

          # Si no hay cambios en microservicios, asignar lista vacía
          if [[ -z "$detected_services" ]]; then
            echo "No hay microservicios modificados."
            echo "services=[]" >> $GITHUB_OUTPUT
          else
            echo "services=$(echo \"$detected_services\" | jq -R -s -c 'split("\n") | map(select(length > 0))')" >> $GITHUB_OUTPUT
          fi
